# Generated by Django 3.1 on 2020-08-29 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApiFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('api_id', models.CharField(max_length=128, verbose_name='Google drive folder ID')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Title')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.googleapifolder', verbose_name='Google drive folder with group data')),
                ('users', models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(verbose_name='Solution text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Rejected at')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ('number', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to=report.models.task_file_path, verbose_name='Task file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_file', to='report.task', verbose_name='Task')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to=report.models.source_report_path, verbose_name='Source file')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='report.report', verbose_name='Report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportsFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.googleapifolder', verbose_name='Google drive folder for storing reports')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_folders', to='report.group', verbose_name='Group')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_folders', to='report.task', verbose_name='Task')),
            ],
            options={
                'ordering': ('group', 'task'),
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to=report.models.report_file_path, verbose_name='Report file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='report.report', verbose_name='Report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.task'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
