# Generated by Django 2.2.6 on 2019-11-02 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.FileField(upload_to='tasks/', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(verbose_name='Solution text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Approved at')),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Rejected at')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Title')),
                ('upload_link', models.CharField(max_length=256, verbose_name='Upload link')),
                ('users', models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=report.models.report_path, verbose_name='Source file')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='report.Report', verbose_name='Report')),
            ],
        ),
    ]
