# Generated by Django 2.2.6 on 2019-11-01 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, verbose_name='Path to file')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='report.File', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField(verbose_name='Solution text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('files', models.ManyToManyField(blank=True, related_name='reports', to='report.File', verbose_name='Files')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('upload_link', models.CharField(max_length=256, verbose_name='Upload link')),
                ('users', models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
