# Generated by Django 2.2.6 on 2019-12-30 08:26

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=256, upload_to=report.models.report_path, verbose_name='Source file'),
        ),
    ]
