# Generated by Django 3.1.2 on 2020-10-16 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_delete_reportsfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(verbose_name='Ratio')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_left', to='report.report', verbose_name='Left')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_right', to='report.report', verbose_name='Right')),
            ],
        ),
    ]
